# Generated by Django 6.0.3 on 2026-04-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
